# Generated by Django 3.0.13 on 2021-02-26 02:18

import chunked_upload.settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChunkedUpload',
            fields=[
                ('chunkedupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chunked_upload.ChunkedUpload')),
            ],
            options={
                'abstract': False,
            },
            bases=('chunked_upload.chunkedupload',),
        ),
    ]
